Log feature importance, add internal use metadata api
sigopt/sigopt-python pull request #279
Opened 2021-10-28 18:07 UTC by yuhong-sigopt

2021-10-29 19:39 UTC, yuhong-sigopt commented on sigopt/xgboost/run.py
> +    scores = dict(sorted(scores.items(), key=lambda x:-x[1])[:FEATURE_IMPORTANCE_MAX_NUM_FEATURE])
`scores[:M] is equal to score[:min(len(scores), M)]`. 

`reverse=True` is changed.

2021-10-29 20:10 UTC, yuhong-sigopt commented on integration_test/test_xgboost.py
>  class TestXGBoost(object):
Done.

2021-10-29 20:14 UTC, ericlee0803 approved these changes
the addition of feature importance inside xgboost/runs.py and associated test looks fine to me, I defer to others as far as the rest of the code is concerned.

2021-10-29 22:21 UTC, ericlee0803 commented
@yuhong-sigopt can you rebase? Just merged in a PR for the metrics logging

2021-10-29 22:21 UTC, ericlee0803 requested changes
rebase off metric logging PR

2021-10-30 02:19 UTC, yuhong-sigopt commented
> @yuhong-sigopt can you rebase? Just merged in a PR for the metrics logging

Done.

2021-10-30 02:19 UTC, yuhong-sigopt commented
> rebase off metric logging PR

Done.

2021-11-01 16:14 UTC, ericlee0803 approved these changes

2021-11-01 16:20 UTC, merged